In [3]:
#Q1
import numpy as np
np.arange(2,50,3)
    


array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [35]:
#Q2
lst1=[]
lst2=[]
for i in range(0,5):
    ele1=int(input())
    ele2=int(input())
    lst1.append(ele1)
    lst2.append(ele2)
print("array 1")
print(lst1)
print("array 2")
print(lst2)
lst1=np.array(lst1)
lst2=np.array(lst2)
arr=np.concatenate((lst1,lst2))
print("concatenated list")
print(arr)
sortedArr=np.sort(arr)
print("sorted list")
print(sortedArr)
    

1
2
3
4
5
6
7
8
9
10
array 1
[1, 3, 5, 7, 9]
array 2
[2, 4, 6, 8, 10]
concatenated list
[ 1  3  5  7  9  2  4  6  8 10]
sorted list
[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
#Q3
arr2D = np.array([[1 ,2,3,4], [5,6,7,8], [9,10,11,12]])
print('2D Numpy Array')
print(arr2D)
numOfRows = np.size(arr2D, 0)
numOfColumns = np.size(arr2D, 1)
print("DIMENSION")
print('Number of Rows : ', numOfRows)
print('Number of Columns : ', numOfColumns)
print('Total Number of elements in 2D Numpy array : ', np.size(arr2D))

2D Numpy Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
DIMENSION
Number of Rows :  3
Number of Columns :  4
Total Number of elements in 2D Numpy array :  12


In [43]:
#Q4
arr_1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10])
print('1D Numpy array:')
print(arr_1D)
print("\n1D array converted into 2D numpy array")
arr_2d = np.reshape(arr, (2,5 ))
print(arr_2d)

1D Numpy array:
[ 1  2  3  4  5  6  7  8  9 10]

1D array converted into 2D numpy array
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [54]:
#Q5
arr1 = np.array([4,9,12])
arr2 = np.array([16,25,36])
vs=np.vstack((arr1,arr2))
hs=np.hstack((arr1,arr2))
print("vertical stack")
print(vs)
print("\nhorizontal stack")
print(hs)

vertical stack
[[ 4  9 12]
 [16 25 36]]

horizontal stack
[ 4  9 12 16 25 36]


In [59]:
#Q6
def unique(list1): 
    x = np.array(list1) 
    print(np.unique(x)) 
       
list1 = [10, 20, 10, 30, 40, 40] 
print("the unique values from 1st list is") 
unique(list1) 
new_set = set(list1) 
print("No of unique items in the list are:", len(new_set))
  


the unique values from 1st list is
[10 20 30 40]
No of unique items in the list are: 4
